### ISSUE TITLE
Search function need to be fully implemented

### ISSUE THREAD

**Issue by wangweiweinimeng** [computationalmystic/augur-group19#2]
The search function can return projects which contains the key words. But now it cannot go very well with sorting function. If we do a searching first and then do a sorting , it will show all projects.

**Comment by sgoggins** [comment]
What is it we are sorting for? By? What criteria? There needs to be more description and this is probably several use cases.

**Comment by wangweiweinimeng** [comment]
Describe the bug:
The search function cannot return result now.

To Reproduce:
Steps to reproduce the behavior:

Go to http://ec2-3-17-10-157.us-east-2.compute.amazonaws.com:3333
Type in some key words in searchbar
Click the "Search" button
The results don't search at all.It may have something to do with the search function:
  search() {
    var searchItem=document.getElementById('searchSelect').value;
    var searchedProjects=this.$data.projects;
    var searchResult=[];
    for (var i=0; i< searchedProjects.length;i++){
      if(searchedProjects[i].indexOf(searchItem)>='0'){
        searchResult.push(searchedProjects[i]);
      }
    }
    return searchResult;
  },
Expected behavior:
When users put key words in search bar and click the search button, only the repos which contain key words would be left.

Desktop :

OS: Ubuntu 16.04
Browser: Google Chrome
Version 73.0.3683.86 (Official Build) (64-bit)

**Comment by wangweiweinimeng** [comment]
Describe the bug:
The search function can return search result now, and it goes along well with sort function.When we search for certain key words ,it will return projects only containing these key words.And if we do sort, it will sort among these projects, which is what we expect. 
But here comes another problem: since we use javascript to parse through the page to get all projects,  it will only search among the projects on the page ,not all the projects in database.(For example, if we do search among 100 projects for the first time ,it returns 10 results.And we do search again, it will only search through these 10 projects rather than the whole 100 projects if we do not refresh the page.)
To Reproduce:
Steps to reproduce the behavior:

Go to http://ec2-18-144-72-47.us-west-1.compute.amazonaws.com:3333/
Type in some key words in searchbar
Click the "Search" button
It will return search results. 
If you do another search without refreshing the page, it will only search through the projects based on the first-time search results.

Expected behavior:
Whenever users put key words in search bar and click the search button, all the repos in database which contain key words would be returned.

Desktop :

OS: Ubuntu 16.04
Browser: Google Chrome
Version 73.0.3683.86 (Official Build) (64-bit)

**Comment by wangweiweinimeng** [comment]
We solved the problem by loading all projects every time before searching.[Using this.$data.projects = Object.keys(this.$data.repos)]
So we don't need to refresh the page to get all results if we want to use new key words for searching.
Search function is working now.
