### ISSUE TITLE
Search results cannot be returned in right order if we do sorting before

### ISSUE THREAD

**Issue by wangweiweinimeng** [computationalmystic/augur-group19#3]
Describe the bug:
When we do testing on our projects, we found that if we sort from ZtoA first, all projects will be in right order. And then if we do search 'red' ,all the search results will be returned correctly except that they are not in ZtoA order. But if we do sort again, they will be in right order.

1.Go to http://ec2-18-144-72-47.us-west-1.compute.amazonaws.com:3333/
2.Choose ZtoA and click the Sort button
3.Type in some key words in search bar, like 'red'
4.Click the "Search" button
It will return search results but not in ZtoA order anymore.
If you do sort ZtoA again , the search results will be in exact right order.

Expected behavior:
If we do sort first and then do search, the returned results should be in order which was chosen before.

Desktop :

OS: Ubuntu 16.04
Browser: Google Chrome
Version 73.0.3683.86 (Official Build) (64-bit)

**Comment by thomasjurczyk** [comment]
Fixed this issue by calling the sort function after a search is run.
